// <auto-generated />
using System;
using Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace leltar.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20190812114303_Database expand")]
    partial class Databaseexpand
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inventory.Model.InventoryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BruttoErtek");

                    b.Property<DateTime>("ElhelyezesIdeje");

                    b.Property<int>("EszkozAzon");

                    b.Property<string>("GyariSzam");

                    b.Property<DateTime>("HasznalatbaVetelDatuma");

                    b.Property<int>("LeltSzemely");

                    b.Property<string>("LeltSzemelyNeve");

                    b.Property<string>("LeltarKorzet");

                    b.Property<string>("LeltarKorzetMegnevezes");

                    b.Property<string>("LeltariSzam");

                    b.Property<string>("Megnevezes");

                    b.Property<int>("Mennyiseg");

                    b.Property<string>("Vonalkod");

                    b.HasKey("Id");

                    b.ToTable("InventoryDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
